# Tasca S12.01. APIs 

Aplicaràs el que has après sobre APIs REST, mètodes HTTP i codis d'estat, utilitzant APIs públiques per consultar dades, filtrar-les i finalment desar-les en un DataFrame de pandas.

Recursos:

Nivell 1:  
[{JSON} Placeholder](https://jsonplaceholder.typicode.com/)

Nivell 2:  
[Try Public APIs for free](https://github.com/public-apis/public-apis)

Nivell 3:  
[Open Data BCN](https://opendata-ajuntament.barcelona.cat/ca/desenvolupadors#APIS)

In [1]:
import requests
from requests.exceptions import HTTPError
import pandas as pd

## Nivell 1
Des d’un Jupyter Notebook faràs els següents exercicis utilitzant la llibreria requests de Python.
Exploració bàsica amb una API de laboratori.

### 1. Consulta l’API pública JSONPlaceholder utilitzant el mètode GET per obtenir:

o	Llista de publicacions (/posts)

o	Llista d’usuaris (/users)

o	Llista de tasques (/todos)


### 2. Mostra per pantalla:

o	La quantitat total de cada recurs.

o	El codi d'estat de cada petició.

In [2]:
url = "https://jsonplaceholder.typicode.com/"

endpoints = ["/posts", "/users", "/todos"]

for endpoint in endpoints:
    try:
  
        response = requests.get(f"{url}{endpoint}") 
        response.raise_for_status()
        
    
        data = response.json()
        print(f"\n{endpoint}\n{data}")
        print(f"Recurs {endpoint}: S'han obtingut {len(data)} elements. Codi: {response.status_code}")
        
    except requests.exceptions.HTTPError as err:
        print(f"Error HTTP en obtenir {endpoint}: {err}")
    except Exception as e:
        print(f"S'ha produït un error inesperat: {e}")

/posts

### 3. Fes una petició a una publicació inexistent per obtenir un error 404 i mostra el codi d'estat rebut.

In [3]:
error_req = requests.get(f"{url}/error")
try:
    error_req.raise_for_status()
except requests.exceptions.HTTPError as e:
        print(f"Error HTTP: {e}")

Error HTTP: 404 Client Error: Not Found for url: https://jsonplaceholder.typicode.com//error

### 4. Fes una petició POST per crear una nova publicació fictícia. Inclou el títol, el cos del missatge i un userId.

o	Mostra la resposta JSON.
o	Mostra el codi d'estat.

In [4]:
nova_publicacio = {
    "title": "Primer post de prova",
    "body": "Aquest és un missatge creat amb Python",
    "userId": 122
}

resposta = requests.post("https://jsonplaceholder.typicode.com/posts", json=nova_publicacio)

print("JSON respuesta:", resposta.json())
print("Status:", resposta.status_code)

JSON respuesta: {'title': 'Primer post de prova', 'body': 'Aquest és un missatge creat amb Python', 'userId': 122, 'id': 101}
Status: 201

### 5. Fes una petició PATCH per modificar parcialment una publicació existent.
o	Mostra la resposta JSON.
o	Mostra el codi d'estat.

In [5]:
canvi = {"title": "Títol modificat", "body": "Modificació feta per a l'exercici 5 del nivell 1" }

resposta = requests.patch(
    "https://jsonplaceholder.typicode.com/posts/101",
    json=canvi
)

print("JSON respuesta:", resposta.json())
print("Status:", resposta.status_code)

JSON respuesta: {'title': 'Títol modificat', 'body': "Modificació feta per a l'exercici 5 del nivell 1"}
Status: 200

### 6. Fes una petició DELETE sobre una publicació.
o	Mostra la resposta JSON.
o	Mostra el codi d'estat.

In [6]:
response_delete = requests.delete(f"{url}/posts/101")

print(response_delete.json())
print("Status:", response_delete.status_code)

{}
Status: 200

## Nivell 2

Interacció amb una API pública real

### 1. Explora el repositori de Public APIs i tria una API que permeti fer peticions GET.

Usarem la api: https://www.tvmaze.com/api

### 2. Llegeix la documentació de l'API:

**Revisa la secció d’endpoints disponibles. En un markdown, apunta com a mínim dos endpoints diferents.**

Endpoint 1: /search/shows?q=nom - Permet cercar sèries per nom.
Endpoint 2: /shows

**Comprova si ofereix filtres o paràmetres opcionals interessants. En un markdown, anota’ls.**

La TVMaze API ofereix diversos paràmetres que permeten personalitzar les consultes i obtenir informació més específica.

1. q (query)

S'utilitza per cercar una sèrie o una persona pel seu nom.

Exemple:

https://api.tvmaze.com/search/shows?q=friends



2. country

Permet filtrar la programació d'episodis per país utilitzant codis ISO 3166-1.

Exemple:

https://api.tvmaze.com/schedule?country=ES

https://api.tvmaze.com/schedule?country=GB

Si no s'indica, el valor per defecte és US.


3. date

Permet consultar la programació d'una data concreta.

Format:

YYYY-MM-DD

Exemple:

https://api.tvmaze.com/schedule?date=2026-06-15

**Verifica que la resposta sigui en format JSON (és el més adequat per a aquest exercici).**

In [7]:
response = requests.get("https://api.tvmaze.com/search/shows")
print(response.headers["Content-Type"])

application/json; charset=UTF-8

Mirem la capçalera de "Content-Type" del protocol HTTP per veure el format en el que s'envien les dades. Com que veiem que retorna "application/json; charset=UTF-8" indica que la resposta esà en format JSON

### 3. Fes una petició GET senzilla:

o	Mostra el codi d'estat de la resposta.

o	Imprimeix de forma clara alguns dels camps de la resposta JSON.

In [10]:
# Cercarem sèries que continguin "Batman"
url_2 = "https://api.tvmaze.com/search/shows"
params = {'q': 'batman'}

try:
    response = requests.get(url_2, params=params)
    response.raise_for_status() 
    print(f"Codi d'estat: {response.status_code}")
    
    data = response.json()
    

    for entry in data[:3]:
        show = entry['show']
        print(f"Sèrie: {show['name']}, Gèneres: {', '.join(show['genres'])}")
        
except requests.exceptions.HTTPError as err:
    print(f"Error HTTP: {err}")

Codi d'estat: 200
Sèrie: Batman, Gèneres: Comedy, Action, Adventure
Sèrie: Batman Beyond, Gèneres: Action, Adventure, Science-Fiction
Sèrie: Batman Unlimited, Gèneres: Action, Children, Science-Fiction

### 4. Converteix les dades a un DataFrame de pandas:

o	Mostra les primeres files del DataFrame.

In [11]:
# Extraiem només la informació de 'show' per a cada resultat
show_list = [entry['show'] for entry in data]
df = pd.DataFrame(show_list)


df.head()

,id,url,name,type,language,genres,status,runtime,averageRuntime,premiered,...,rating,weight,network,webChannel,dvdCountry,externals,image,summary,updated,_links
0,975,https://www.tvmaze.com/shows/975/batman,Batman,Scripted,English,"[Comedy, Action, Adventure]",Ended,30.0,30,1966-01-12,...,{'average': 7.8},97,"{'id': 3, 'name': 'ABC', 'country': {'name': '...",None,None,"{'tvrage': 2719, 'thetvdb': 77871, 'imdb': 'tt...",{'medium': 'https://static.tvmaze.com/uploads/...,<p>Wealthy entrepreneur Bruce Wayne and his wa...,1778378492,{'self': {'href': 'https://api.tvmaze.com/show...
1,504,https://www.tvmaze.com/shows/504/batman-beyond,Batman Beyond,Animation,English,"[Action, Adventure, Science-Fiction]",Ended,30.0,30,1999-01-10,...,{'average': 8},96,"{'id': 71, 'name': 'The WB', 'country': {'name...",None,None,"{'tvrage': 2722, 'thetvdb': 75417, 'imdb': 'tt...",{'medium': 'https://static.tvmaze.com/uploads/...,<p><b>Batman Beyond</b> tells the story of Ter...,1704793633,{'self': {'href': 'https://api.tvmaze.com/show...
2,11464,https://www.tvmaze.com/shows/11464/batman-unli...,Batman Unlimited,Animation,English,"[Action, Children, Science-Fiction]",Ended,4.0,4,2015-05-04,...,{'average': 6.3},82,None,"{'id': 21, 'name': 'YouTube', 'country': None,...",None,"{'tvrage': None, 'thetvdb': 301558, 'imdb': None}",{'medium': 'https://static.tvmaze.com/uploads/...,<p>A webseries began airing on DC Kids' YouTub...,1588682864,{'self': {'href': 'https://api.tvmaze.com/show...
3,481,https://www.tvmaze.com/shows/481/the-batman,The Batman,Animation,English,"[Action, Adventure, Science-Fiction]",Ended,30.0,30,2004-09-11,...,{'average': 7.7},79,"{'id': 5, 'name': 'The CW', 'country': {'name'...",None,None,"{'tvrage': 5602, 'thetvdb': 73180, 'imdb': 'tt...",{'medium': 'https://static.tvmaze.com/uploads/...,"<p>Hidden in the shadows, The Batman casts a p...",1704793623,{'self': {'href': 'https://api.tvmaze.com/show...
4,55415,https://www.tvmaze.com/shows/55415/batman-cape...,Batman: Caped Crusader,Animation,English,"[Drama, Action, Crime]",Running,NaN,26,2024-08-01,...,{'average': 7.2},99,None,"{'id': 3, 'name': 'Prime Video', 'country': No...",None,"{'tvrage': None, 'thetvdb': 403170, 'imdb': 't...",{'medium': 'https://static.tvmaze.com/uploads/...,"<p>Welcome to Gotham City, where the corrupt o...",1780592846,{'self': {'href': 'https://api.tvmaze.com/show...

## Nivell 3

[API d'Open Data Barcelona](https://opendata-ajuntament.barcelona.cat/ca/desenvolupadors#APIS)

### 1. Utilitza l’API d’Open Data BCN per:

1.a.	Cercar un dataset del teu interès mitjançant package_search

In [12]:
url_3 = "https://opendata-ajuntament.barcelona.cat/data/api/action/"
params_search = {"q":"multes"}

resposta_search = requests.get(f"{url_3}/package_search", params=params_search) 

try:
    resposta_search.raise_for_status()
    print(f"Status: {resposta_search.status_code}")

    resultats = resposta_search.json()

    print("Datasets trobats:")
    print(len(resultats["result"]["results"]))

    datasets = resultats["result"]["results"]

    for ds in datasets[:10]:
        print("Títol:", ds["title"])
        print("ID:", ds["id"])
        print("--------------")

except requests.exceptions.HTTPError as e:
        print(f"Error HTTP: {e}")

Status: 200
Datasets trobats:
4
Títol: Vehicle types in traffic complaints and sanctions processed by the Institut Municipal d’Hisenda of Barcelona City Council
ID: bf7a733a-1faa-4ec8-ba1d-b4461df9f84a
--------------
Títol: Official coding of traffic complaints and sanctions processed by the Institut Municipal d’Hisenda of Barcelona City Council
ID: b388d80c-8a96-495a-99a0-a0c2c0b9de10
--------------
Títol: Related concepts with traffic complaints and sanctions processed by the Institut Municipal d’Hisenda of Barcelona City Council
ID: 26eefc76-bd48-4dcd-8402-b43f4a86cd6f
--------------
Títol: Detail of traffic complaints and sanctions processed by the Institut Municipal d’Hisenda of Barcelona City Council
ID: ce80eb0b-0d99-4470-94f8-b09ce818b061
--------------

*1.B package_show*

In [13]:

##Agafem el id del quart dataset dels obtinguts per exemple
dataset_id = datasets[0]["name"]

print (dataset_id)


url_4 = "https://opendata-ajuntament.barcelona.cat/data/api/action/package_show"

params = {"id": dataset_id}

resposta_show = requests.get(url_4, params=params)
resposta_show.raise_for_status()

dades_show = resposta_show.json()


print("Títol:", dades_show["result"]["title"])
print("Número de recursos:", len(dades_show["result"]["resources"]))

# Mostrar los primeros 3 recursos
for recurs in dades_show["result"]["resources"]:
    print("Nombre:", recurs["name"])
    print("Formato:", recurs["format"])
    print("Resource ID:", recurs["id"])
    print("-------------")

denuncies_sancions_transit_bcn_tip_vehicle
Títol: Vehicle types in traffic complaints and sanctions processed by the Institut Municipal d’Hisenda of Barcelona City Council
Número de recursos: 8
Nombre: 2025_denuncies_sancions_transit_tipus_vehicle.csv
Formato: CSV
Resource ID: 0ad04b34-c306-4d88-bd7f-dbead3926ec3
-------------
Nombre: 2025_denuncies_sancions_transit_tipus_vehicle.json
Formato: JSON
Resource ID: ee416b0d-5b12-4acf-967c-137116afd069
-------------
Nombre: 2024_denuncies_sancions_transit_tipus_vehicle.csv
Formato: CSV
Resource ID: d42a2586-b675-4691-af9e-e5b4b71066a7
-------------
Nombre: 2024_denuncies_sancions_transit_tipus_vehicle.json
Formato: JSON
Resource ID: 78a96d4c-4e14-42ec-a6e5-89fbeffa9cf1
-------------
Nombre: 2023_denuncies_sancions_transit_tipus_vehicle.csv
Formato: CSV
Resource ID: 93cc8547-55af-407c-b1ea-160574ab0c89
-------------
Nombre: 2023_denuncies_sancions_transit_tipus_vehicle.json
Formato: JSON
Resource ID: b0c98620-c989-424b-991e-16033f869125
-------------
Nombre: 2022_denuncies_sancions_transit_tipus_vehicle.csv
Formato: CSV
Resource ID: 802f0653-5b01-413f-b8ce-9e2b676a58b7
-------------
Nombre: 2022_denuncies_sancions_transit_tipus_vehicle.json
Formato: JSON
Resource ID: c55d1c5e-69da-47e4-b56e-1ecb676627a2
-------------

### 2. Dels resultats obtinguts, selecciona’n un que tingui recursos disponibles en CSV o JSON.

In [14]:
resource_id = None
recursos = dades_show["result"]["resources"]

for recurs in recursos:
    format_recurs = recurs["format"].lower()
    
    if format_recurs in ["csv", "json"]:
        resource_id = recurs["id"]
        print(f"\nRecursos seleccionat: {recurs['name']} (Format: {recurs['format']})")
        print(f"Resource ID: {resource_id}")
        break

Recursos seleccionat: 2025_denuncies_sancions_transit_tipus_vehicle.csv (Format: CSV)
Resource ID: 0ad04b34-c306-4d88-bd7f-dbead3926ec3

### 3. Amb el resource_id del recurs seleccionat, realitza una consulta mitjançant datastore_search per:

o	Recuperar almenys 100 registres.

In [15]:
if resource_id:
    url_datastore = "https://opendata-ajuntament.barcelona.cat/data/api/action/datastore_search"
    
    params_datastore = {
        "resource_id": resource_id,
        "limit": 100
    }
    
    resposta_ds = requests.get(url_datastore, params=params_datastore)
    resposta_ds.raise_for_status()
    
    dades_records = resposta_ds.json()
    
    llista_registres = dades_records["result"]["records"]
    
    print(f"\nS'han recuperat {len(llista_registres)} registres correctament.")
    
    if llista_registres:
        print("Exemple del primer registre:", llista_registres[0])
else:
    print("No s'ha trobat cap recurs en format CSV o JSON en aquest dataset.")

S'han recuperat 40 registres correctament.
Exemple del primer registre: {'Tipus_Vehicle_Codi': 'AB', 'Tipus_Vehicle_Desc_ES': 'AUTOBUS', '_id': 1, 'Tipus_Vehicle_Desc_CA': 'AUTOBUS'}

### 4. Converteix els resultats a un DataFrame.

In [18]:
df = pd.DataFrame(llista_registres)
df

,Tipus_Vehicle_Codi,Tipus_Vehicle_Desc_ES,_id,Tipus_Vehicle_Desc_CA
0,AB,AUTOBUS,1,AUTOBUS
1,AC,AUTOCAR,2,AUTOCAR
2,AM,AMBULANCIA,3,AMBULANCIA
3,AP,,4,APISONADORA
4,BA,,5,BICICLETA AMB PEDALEIG ASSISTIT
5,BT,,6,BICICLETA
6,C,CAMIÓN,7,CAMIÓ
7,CC,,8,CICLE MÉS DE DUES RODES C2 PER CÀRREGA
8,CL,COMERCIAL,9,COMERCIAL
9,CM,VELOMOTORES,10,CICLOMOTOR
10,CP,,11,CICLE MÉS DE DUES RODES C1 TRANSPORTS DE PERSONES
11,CR,,12,CICLE DE MOTOR FINS A 1000W
12,CT,CAMIONETAS,13,CAMIONETES
13,F,FURGONETA,14,FURGONETA
14,G,GRÚA,15,GRUA
15,GI,,16,GINY MECÀNIC
16,IR,VEH.ARRASTRE,17,VEH.ARROSEGAMENT
17,M,MOTO,18,MOTO
18,MB,,19,MICROBÚS
19,MC,MOTO-CARRO,20,MOTO-CARRO
20,MP,,21,MONOPATÍ
21,MS,MOTO-SIDE,22,MOTO-SIDE
22,P,PALA,23,PALA
23,PC,PALA CARGADORA,24,PALA CÀRREGA
24,PT,,25,PATINS
25,QC,CUADRICICLO,26,QUADRICICLE
26,QP,,27,QUADRICICLE PESAT
27,RI,REMOLQUE IND.,28,REMOLC IND.
28,RT,REMOLQUE TUR.,29,REMOLC TUR.
29,T,TURISMO,30,TURISME
30,TA,TAXI,31,TAXI
31,TL,TRICICLO,32,TRICICLE
32,TR,TRACTOR,33,TRACTOR
33,TT,TODO TERRENO,34,TOT TERRENY
34,VE,VEH.ESPECIAL,35,VEH.ESPECIAL
35,VI,,36,VIANANT
36,VL,VELOMOTORES,37,VELOMOTORS
37,VM,VEHICULO MIXTO,38,VEHICLE MIXT
38,VP,,39,V.MOBIL PERSONAL
39,VV,VEH.VIVIENDA,40,VEH. HABITATGE

### 5. Desa el DataFrame en un fitxer .csv.

In [19]:
df.to_csv("tipus_vehicles_multes.csv", index=False)